[project]
name = 'Decentralized-Carbon-Credit-Trading-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.carbon-credit-issuance]
path = 'contracts/carbon-credit-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.credit-trading]
path = 'contracts/credit-trading.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-verification]
path = 'contracts/project-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.retirement]
path = 'contracts/retirement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
